### ISSUE TITLE
Errors when Submiting player data

### ISSUE THREAD

**Issue by Feuxlin** [TemporalAgent7/datacore#15]
When submitting the attached (Player.txt) data to https://datacore.netlify.com/voyage i get the following errors
1. When calculating voyages I get a black screen and the console shows 3 errors (Errors.txt)
2. When attempting to share the profile I get a spinning wheel when clicking and a single error (Error2.txt)
[Player.txt](https://github.com/TemporalAgent7/datacore/files/3668881/Player.txt)
[Error.txt](https://github.com/TemporalAgent7/datacore/files/3668882/Error.txt)
[Error2.txt](https://github.com/TemporalAgent7/datacore/files/3668883/Error2.txt)

**Comment by TemporalAgent7** [comment]
That player data looks wrong. There is no crew or items or ships on the account. Is it possible you were logged in with the wrong DBID?
Perhaps you created an account for the forums, which is separate from the game account, and you never actually logged into the game with the forum account; that's the only potential explanation that comes to mind.
Try loading the player data from an incognito window and make sure to log in with the same credentials you use in the game.

**Comment by Feuxlin** [comment]
Its what I was provided, Let me get with the user and see if I can do a test login from another device.

**Comment by Feuxlin** [comment]
Thanks @TemporalAgent7, that was exactly what it was :/ Sorry to have wasted your time.
