### ISSUE TITLE
Charts & stats not working

### ISSUE THREAD

**Issue by Ricardo1701** [TemporalAgent7/datacore#17]
The Charts & stats page on the profile is not working, when I click it, the whole UI disappears, tested on Firefox 71.0 (64 bits) and on Google Chrome 79.0.3945.88 (64 bits) both on regular browsing and private browising, here is a screen shot of what happens when clicking: https://i.imgur.com/cFHklRi.png

Profile page that it's not working: https://datacore.app/profile/?dbid=1080765614885890

Edit: Now it shows this error message: 

Oops! Something went wrong. Please log a GitHub bug or contact me at admin@datacore.app with these details:

TypeError: q is undefined

**Comment by klobetime** [comment]
I see the same thing, although the error message reads `TypeError: Cannot read property 'legends' of undefined`

**Comment by TemporalAgent7** [comment]
I think it should be fixed now, I had to downgrade the nivo charting packages. Can you give it a try?

**Comment by klobetime** [comment]
Yup -- looks great!  The black on navy legend for the top chart and the hovers for the others is a bit hard to ready, but very pretty otherwise.
Thanks!

**Comment by Ricardo1701** [comment]
Solved, thanks!
