### ISSUE TITLE
voyage calculator showing "error" instead of crew members

### ISSUE THREAD

**Issue by edjusted** [TemporalAgent7/datacore#18]
This has been happening for the past few days.

On the https://datacore.app/voyage site, I copy and paste my data into the voyage calculator, and click "Calculate best crew selection".

Instead of actual crew names, I get something like this:

Estimated duration: 8H 18M

First Officer : ERROR!
Helm Officer : ERROR!
Communications Officer : ERROR!
Diplomat : ERROR!
Chief Security Officer : ERROR!
Tactical Officer : ERROR!
Chief Engineer : ERROR!
Engineer : ERROR!
Chief Science Officer : ERROR!
Deputy Science Officer : ERROR!
Chief Medical Officer : ERROR!
Ship's Counselor : ERROR!

This *was* working for me until a few days ago.

**Comment by edjusted** [comment]
Here's my player.json file.

[player.json.zip](https://github.com/TemporalAgent7/datacore/files/4206103/player.json.zip)

**Comment by TemporalAgent7** [comment]
Thank you, I found the issue and pushed a fix.

It was because you don't have an avatar (no captain picture). The code was assuming that is always present and was bailing out early if it didn't find it.

**Comment by edjusted** [comment]
Wow, you're awesome. Yeah, I know I'm in the minority, but I like the default badge instead of an avatar.

It's working now. Thanks!

**Comment by webdawg77** [comment]
Sounds good,, thank you for the hard work
